{
 "title": "Node Exporter Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Filesystem Free Space",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\n1 -\nnode_filesystem_avail_bytes{fstype!=\"tmpfs\",fstype!=\"overlay\"}\n/\nnode_filesystem_size_bytes{fstype!=\"tmpfs\",fstype!=\"overlay\"}\n)\n*100",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Free RAM",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "memory_free" }
   ]
  },
  { "title": "CPU LA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load 1m" },
    { "expr": "node_load5", "legendFormat": "Load 5m" },
    { "expr": "node_load15", "legendFormat": "Load 15m" }
   ]
  },
  { "title": "CPU %", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  }
 ]
}