---

clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: IP
      ansible_user: username

vector:
  hosts:
    vector-01:
      ansible_host: IP
      ansible_user: username

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: IP
      ansible_user: username
