apiVersion: v1
kind: ConfigMap

metadata:
  name: nginx-web

data:

  index.html: |
    <!DOCTYPE html>

    <html>

    <head>
      <title>ConfigMap Demo</title>
    </head>

    <body>

      <h1>Hello from ConfigMap</h1>

      <h2>Kubernetes works!</h2>

    </body>

    </html>
